# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'itunes-poc' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'Bond'

  # Pods for itunes-poc

  target 'itunes-pocTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'itunes-pocUITests' do
    # Pods for testing
  end

end
